#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Generates this deployment's secrets ONCE, plus the TLS material and the
# pgAdmin connection file that depend on them.
#
#   ./generate-env.sh https://192.168.8.96
#   ./generate-env.sh https://epp.example.com
#
# Writes, all git-ignored, all next to this script:
#
#   .env                    every secret; compose reads it automatically
#   tls/server.{crt,key}    the certificate `web` serves
#   tls/ca.{crt,key}        the local CA that signed it
#   pgadmin/servers.json    pre-registered connection to the platform database
#   pgadmin/pgpass          that connection's password, 0600, uid 5050
#
# An existing .env is NEVER regenerated, for the same reason gen-env.sh does not
# on the native host: RECOVERY_ESCROW_KEY seals every escrowed BitLocker
# recovery password at rest and MFA_TOTP_KEY seals every authenticator
# enrolment. New values would make all of them unreadable at once, and nobody
# would notice until a machine refused to boot or every administrator was
# locked out. PUBLIC_ORIGIN is the one value this script will update in place.
#
# BACKUP-CRITICAL: .env is the complete secret set for this deployment. Back it
# up together with every database dump.
#
# Nothing is ever printed except variable NAMES.
# ---------------------------------------------------------------------------
set -euo pipefail
umask 077

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_file="${here}/.env"
tls_dir="${here}/tls"
pgadmin_dir="${here}/pgadmin"

origin="${1:-}"
if [ -z "$origin" ]; then
    echo "usage: generate-env.sh https://<host-or-ip>" >&2
    exit 1
fi
# https:// only, no path, no trailing slash: the value is compared against the
# browser's Origin header verbatim, and the session cookie is __Host-/Secure, so
# an http:// origin would produce a platform nobody can sign in to.
if ! [[ "$origin" =~ ^https://[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?(:[0-9]{1,5})?$ ]]; then
    echo "PUBLIC_ORIGIN must be https://<host> with no path and no trailing slash; got: ${origin}" >&2
    exit 1
fi

host_with_port="${origin#https://}"
host="${host_with_port%%:*}"

# Passwords: [A-Za-z0-9] only. They travel through an Npgsql connection string,
# a Redis connection string ("host:6379,password=VALUE"), a compose .env file
# and a pgpass line, and each of those has its own opinion about punctuation.
gen_password() {
    local raw
    raw="$(openssl rand -base64 48 | tr -d '+/=\n')"
    if [ "${#raw}" -lt 32 ]; then
        echo "password generation produced too few characters" >&2
        return 1
    fi
    printf '%s' "${raw:0:32}"
}

# Keys: the services require base64 of EXACTLY 32 bytes; anything else is
# rejected at startup. The padding is part of the value, so nothing is stripped.
gen_key() {
    local key
    key="$(openssl rand -base64 32)"
    if [ "${#key}" -ne 44 ]; then
        echo "key generation produced an unexpected length" >&2
        return 1
    fi
    printf '%s' "$key"
}

# --- 1. secrets, once --------------------------------------------------------

if [ -f "$env_file" ]; then
    echo "==> ${env_file} already exists, keeping every secret in it"

    current_origin="$(grep -E '^PUBLIC_ORIGIN=' "$env_file" | tail -n 1 | cut -d= -f2- || true)"
    if [ "$current_origin" != "$origin" ]; then
        echo "==> PUBLIC_ORIGIN changes: ${current_origin:-<unset>} -> ${origin}"
        tmp="${env_file}.tmp.$$"
        grep -vE '^(PUBLIC_ORIGIN|SERVER_NAME)=' "$env_file" > "$tmp" || true
        printf 'PUBLIC_ORIGIN=%s\nSERVER_NAME=%s\n' "$origin" "$host" >> "$tmp"
        chmod 600 "$tmp"
        mv "$tmp" "$env_file"
    fi
else
    tmp="${env_file}.tmp.$$"
    trap 'rm -f "$tmp"' EXIT

    cat > "$tmp" <<EOF
# ---------------------------------------------------------------------------
# endpoint platform: deployment secrets for the container stack.
#
# Generated by deploy/docker/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# 0600, never printed, never committed.
#
# BACKUP-CRITICAL. This is the complete secret set for this deployment:
#   - the PostgreSQL passwords the database roles were created with
#   - REDIS_PASSWORD
#   - SECRET_PROTECTION_KEY  (in-flight account secrets; rotation is safe)
#   - RECOVERY_ESCROW_KEY    (escrowed BitLocker passwords; LOSS IS PERMANENT)
#   - MFA_TOTP_KEY           (authenticator secrets; LOSS LOCKS EVERY ADMIN OUT)
# Back it up alongside every database dump. generate-env.sh never regenerates it.
# ---------------------------------------------------------------------------

# --- PostgreSQL (no published port; compose network only) --------------------
POSTGRES_DB=endpoint_platform
# Cluster superuser inside the container. Creates the two roles below on first
# initialisation; the application never connects as this role.
POSTGRES_ADMIN_PASSWORD=$(gen_password)
# Owner role: owns the schema and holds DDL rights. Used ONLY by the migration
# job. Despite the historical variable name it is NOT a cluster superuser.
POSTGRES_SUPERUSER=endpoint_owner
POSTGRES_SUPERUSER_PASSWORD=$(gen_password)
# Restricted runtime role used by both APIs: no DDL, INSERT/SELECT only on the
# audit table.
POSTGRES_APP_USER=endpoint_app
POSTGRES_APP_PASSWORD=$(gen_password)

# --- Redis (no published port; compose network only) -------------------------
REDIS_PASSWORD=$(gen_password)

# --- Secret protection (both APIs, identical value) --------------------------
# base64 of 32 random bytes. Rotating only invalidates in-flight secrets.
SECRET_PROTECTION_KEY=$(gen_key)

# --- BitLocker recovery-password escrow (Admin API only) ---------------------
# base64 of 32 random bytes. Rotation does NOT re-seal existing rows: bump the
# version and re-seal before retiring the old key.
RECOVERY_ESCROW_KEY=$(gen_key)
RECOVERY_ESCROW_KEY_VERSION=1

# --- Multi-factor authentication (Admin API only) ----------------------------
# base64 of 32 random bytes, sealing the TOTP secret behind each administrator's
# authenticator app. LOSS IS NOT RECOVERABLE BY RE-ENROLLING ONE PERSON: every
# enrolment becomes unreadable at once. Never given to the Agent API.
MFA_TOTP_KEY=$(gen_key)

# --- Agent release trust mode ------------------------------------------------
# Internal: integrity is the server-computed SHA-256 over HTTPS, no
# Authenticode signature required.
AGENT_RELEASE_TRUST_MODE=Internal

# --- pgAdmin -----------------------------------------------------------------
PGADMIN_EMAIL=admin@endpoint.local
PGADMIN_PASSWORD=$(gen_password)
PGADMIN_PORT=5050
# pgAdmin's per-user storage directory: the login address with '@' as '_'. The
# pass file has to live in there, because that is the only place pgAdmin looks.
PGADMIN_STORAGE_DIR=admin_endpoint.local

# --- Published ports ---------------------------------------------------------
HTTP_PORT=80
HTTPS_PORT=443

# --- Image tagging -----------------------------------------------------------
IMAGE_TAG=local
IMAGE_VERSION=0.1.0

# --- Public origin -----------------------------------------------------------
# The exact https:// origin browsers and agents use. CORS allow-list; the Admin
# API refuses to start without it. SERVER_NAME is the same host for nginx.
PUBLIC_ORIGIN=${origin}
SERVER_NAME=${host}
EOF

    chmod 600 "$tmp"
    mv "$tmp" "$env_file"
    trap - EXIT

    echo "==> wrote ${env_file} (0600) with:"
    grep -oE '^[A-Z_]+=' "$env_file" | tr -d '=' | sed 's/^/      /'
    echo "    back this file up: it holds the escrow key, the MFA key and the database passwords"
fi

chmod 600 "$env_file"

# Upgrade path, for an .env written before the pass file was put in pgAdmin's
# storage directory. Deriving it is safe and destroys nothing; an existing value
# is never touched.
if ! grep -qE '^PGADMIN_STORAGE_DIR=' "$env_file"; then
    pgadmin_email="$(grep -E '^PGADMIN_EMAIL=' "$env_file" | tail -n 1 | cut -d= -f2-)"
    {
        echo ""
        echo "# pgAdmin's per-user storage directory: the login address with '@' as '_'."
        echo "PGADMIN_STORAGE_DIR=${pgadmin_email//@/_}"
    } >> "$env_file"
    echo "==> added PGADMIN_STORAGE_DIR to ${env_file}"
fi

# --- 2. TLS ------------------------------------------------------------------
#
# A local CA signs a certificate for this host. Self-signed is the honest
# option on a private network with no public DNS name: it costs a CA root on
# every machine that talks to the platform, and it is the only way to serve the
# HTTPS origin the __Host- session cookie requires.

mkdir -p "$tls_dir"
# 0755, against the 0077 umask above. nginx reads the private key as root while
# it is still the master process, but it serves /endpoint-platform-ca.crt from a
# WORKER running as an unprivileged user, and that worker has to be able to
# traverse this directory. The keys inside stay 0600.
chmod 755 "$tls_dir"

if [ -f "${tls_dir}/server.crt" ] && [ -f "${tls_dir}/server.key" ]; then
    echo "==> ${tls_dir}/server.crt already exists, keeping it"
    if ! openssl x509 -in "${tls_dir}/server.crt" -noout -checkhost "$host" >/dev/null 2>&1 \
    && ! openssl x509 -in "${tls_dir}/server.crt" -noout -checkip "$host" >/dev/null 2>&1; then
        echo "    WARNING: it does not cover ${host}. Delete ${tls_dir}/ and re-run to reissue."
    fi
else
    echo "==> issuing a certificate for ${host} from a new local CA"

    # An IP address has to appear as IP:, a name as DNS:. Browsers ignore the
    # legacy CN entirely, so getting this wrong means a certificate no client
    # accepts, however loudly it is trusted.
    if [[ "$host" =~ ^[0-9]{1,3}(\.[0-9]{1,3}){3}$ ]]; then
        san="IP:${host}"
    else
        san="DNS:${host}"
    fi

    openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
        -keyout "${tls_dir}/ca.key" -out "${tls_dir}/ca.crt" \
        -subj "/CN=Endpoint Platform local CA" \
        -addext "basicConstraints=critical,CA:TRUE,pathlen:0" \
        -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null

    openssl req -newkey rsa:2048 -sha256 -nodes \
        -keyout "${tls_dir}/server.key" -out "${tls_dir}/server.csr" \
        -subj "/CN=${host}" 2>/dev/null

    # Browsers cap the lifetime of a server certificate; 398 days keeps this one
    # inside every current limit.
    openssl x509 -req -in "${tls_dir}/server.csr" -sha256 -days 398 \
        -CA "${tls_dir}/ca.crt" -CAkey "${tls_dir}/ca.key" -CAcreateserial \
        -out "${tls_dir}/server.crt" \
        -extfile <(printf 'subjectAltName=%s\nbasicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n' "$san") \
        2>/dev/null

    rm -f "${tls_dir}/server.csr"

    # Served over plain HTTP at /endpoint-platform-ca.crt, so a machine that does
    # not trust the CA yet can fetch it.
    cp "${tls_dir}/ca.crt" "${tls_dir}/endpoint-platform-ca.crt"

    chmod 600 "${tls_dir}/ca.key" "${tls_dir}/server.key" "${tls_dir}/ca.srl" 2>/dev/null || true
    chmod 600 "${tls_dir}/ca.key" "${tls_dir}/server.key"
    chmod 644 "${tls_dir}/ca.crt" "${tls_dir}/server.crt" "${tls_dir}/endpoint-platform-ca.crt"

    echo "    ${tls_dir}/server.crt   (${san}, 398 days)"
    echo "    ${tls_dir}/ca.crt       install this on every machine that talks to the platform"
fi

# --- 3. pgAdmin connection ---------------------------------------------------
#
# Rendered from .env every run, so a password change here is picked up by
# re-running this script and recreating the container.

# shellcheck disable=SC1090
set -a; . "$env_file"; set +a

mkdir -p "$pgadmin_dir"

cat > "${pgadmin_dir}/servers.json" <<EOF
{
  "Servers": {
    "1": {
      "Name": "endpoint-platform",
      "Group": "Endpoint Platform",
      "Host": "postgres",
      "Port": 5432,
      "MaintenanceDB": "${POSTGRES_DB}",
      "Username": "${POSTGRES_SUPERUSER}",
      "PassFile": "/pgpass",
      "SSLMode": "prefer",
      "Comment": "Rendered by deploy/docker/generate-env.sh. Connects as the schema owner, which is the role that can read every table."
    }
  }
}
EOF
chmod 644 "${pgadmin_dir}/servers.json"

# Rewritten only when the contents actually change. pgAdmin runs as uid 5050 and
# ignores a pass file it does not own, so the ownership given by the first (root)
# run has to survive every later run made as an ordinary user.
pgpass_line="$(printf 'postgres:5432:%s:%s:%s' "$POSTGRES_DB" "$POSTGRES_SUPERUSER" "$POSTGRES_SUPERUSER_PASSWORD")"
if [ ! -f "${pgadmin_dir}/pgpass" ] || [ "$(cat "${pgadmin_dir}/pgpass" 2>/dev/null)" != "$pgpass_line" ]; then
    printf '%s\n' "$pgpass_line" > "${pgadmin_dir}/pgpass"
    chmod 600 "${pgadmin_dir}/pgpass"
    chown 5050:5050 "${pgadmin_dir}/pgpass" 2>/dev/null \
        || echo "    note: could not chown pgadmin/pgpass to 5050 (needs root); pgAdmin will ask for the database password instead"
fi

echo "==> rendered ${pgadmin_dir}/servers.json and ${pgadmin_dir}/pgpass"
echo
echo "generate-env.sh: done"
