#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Generates the deployment's secrets ONCE, and renders the per-service
# environment files from them on EVERY run.
#
#   sudo bash infra/ubuntu/gen-env.sh https://epp.example.com
#
# Argument: the public origin (https://<host>, no trailing slash). It becomes
# the Admin API's CORS allow-list, which that API refuses to start without.
#
#   /etc/endpoint-platform/secrets.env     source of truth, generated once
#   /etc/endpoint-platform/migrations.env  OWNER database credential
#   /etc/endpoint-platform/admin-api.env   runtime credential + escrow and MFA keys
#   /etc/endpoint-platform/agent-api.env   runtime credential, PUBLIC sealing key only
#
# All four are root:root 0600. systemd reads EnvironmentFile= as PID 1 before it
# drops to the service account, so no application account can open any of them,
# and in particular the Agent API can never read the Admin API's escrow keys.
#
# An existing secrets.env is NEVER regenerated. RECOVERY_ESCROW_KEY seals every
# escrowed BitLocker recovery password at rest; a new one would make all of
# them unreadable, and nobody would notice until a machine refused to boot.
# The PostgreSQL passwords are likewise already set inside the database. The
# one value this script will update in place is PUBLIC_ORIGIN, which is not a
# secret and legitimately changes when the host is renamed.
#
# To change anything else: edit secrets.env, re-run this script to re-render,
# then restart the services (and run setup-postgres.sh / setup-redis.sh if a
# database or Redis password changed, so the servers learn the new value).
#
# BACKUP-CRITICAL: secrets.env is the complete secret set for the deployment.
# Back it up together with every database dump (see README.md).
#
# Nothing is ever printed except variable NAMES.
# ---------------------------------------------------------------------------
set -euo pipefail
umask 077

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=infra/ubuntu/common.sh
. "${script_dir}/common.sh"

require_root "$@"

origin="${1:-}"
if [ -z "$origin" ]; then
    echo "usage: gen-env.sh https://<public-host>" >&2
    exit 1
fi
# https:// only: the session cookie is Secure and __Host- prefixed, so an
# http:// origin would produce a platform nobody can sign in to. No trailing
# slash: the value is compared against the browser's Origin header verbatim.
if ! [[ "$origin" =~ ^https://[A-Za-z0-9]([A-Za-z0-9.-]*[A-Za-z0-9])?(:[0-9]{1,5})?$ ]]; then
    echo "PUBLIC_ORIGIN must be https://<host> with no path and no trailing slash; got: ${origin}" >&2
    exit 1
fi

install -d -m 0750 -o root -g root "$EPP_ETC_DIR"

# Passwords: [A-Za-z0-9] only. They travel through an Npgsql connection string,
# a Redis connection string ("host:6379,password=VALUE"), a redis.conf directive
# and a systemd EnvironmentFile, and each of those has its own opinion about
# punctuation.
gen_password() {
    local raw
    raw="$(openssl rand -base64 48 | tr -d '+/=\n')"
    if [ "${#raw}" -lt 32 ]; then
        echo "password generation produced too few characters" >&2
        return 1
    fi
    printf '%s' "${raw:0:32}"
}

# Keys: the services require base64 of EXACTLY 32 bytes; anything else is
# rejected at startup. No stripping here, the padding is part of the value.
gen_key() {
    local key
    key="$(openssl rand -base64 32)"
    if [ "${#key}" -ne 44 ]; then
        echo "key generation produced an unexpected length" >&2
        return 1
    fi
    printf '%s' "$key"
}

# --- 1. secrets, once --------------------------------------------------------

if [ -f "$EPP_SECRETS_FILE" ]; then
    echo "==> ${EPP_SECRETS_FILE} already exists, keeping every secret in it"

    current_origin="$(grep -E '^PUBLIC_ORIGIN=' "$EPP_SECRETS_FILE" | tail -n 1 | cut -d= -f2- || true)"
    if [ "$current_origin" != "$origin" ]; then
        echo "==> PUBLIC_ORIGIN changes: ${current_origin:-<unset>} -> ${origin}"
        tmp="${EPP_SECRETS_FILE}.tmp.$$"
        grep -vE '^PUBLIC_ORIGIN=' "$EPP_SECRETS_FILE" > "$tmp" || true
        printf 'PUBLIC_ORIGIN=%s\n' "$origin" >> "$tmp"
        chmod 600 "$tmp"
        mv "$tmp" "$EPP_SECRETS_FILE"
    fi
else
    pg_owner_password="$(gen_password)"
    pg_app_password="$(gen_password)"
    redis_password="$(gen_password)"
    secret_protection_key="$(gen_key)"
    recovery_escrow_key="$(gen_key)"
    mfa_totp_key="$(gen_key)"

    tmp="${EPP_SECRETS_FILE}.tmp.$$"
    trap 'rm -f "$tmp"' EXIT

    cat > "$tmp" <<EOF
# ---------------------------------------------------------------------------
# endpoint platform: deployment secrets
#
# Generated by infra/ubuntu/gen-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# root:root 0600, never printed, never committed.
#
# BACKUP-CRITICAL. This is the complete secret set for this deployment:
#   - the PostgreSQL passwords the database roles were created with
#   - REDIS_PASSWORD
#   - SECRET_PROTECTION_KEY  (in-flight account secrets; rotation is safe)
#   - RECOVERY_ESCROW_KEY    (escrowed BitLocker passwords; LOSS IS PERMANENT)
#   - MFA_TOTP_KEY           (authenticator secrets; LOSS LOCKS EVERY ADMIN OUT)
# Back it up alongside every database dump. gen-env.sh never regenerates it.
#
# After editing: sudo bash infra/ubuntu/gen-env.sh <origin>   (re-renders the
# per-service files), then restart the services.
# ---------------------------------------------------------------------------

# --- PostgreSQL (loopback only) ----------------------------------------------
POSTGRES_DB=endpoint_platform
# Owner role: owns the schema and holds DDL rights. Used ONLY by the migration
# job. Despite the historical variable name it is NOT a cluster superuser.
POSTGRES_SUPERUSER=endpoint_owner
POSTGRES_SUPERUSER_PASSWORD=${pg_owner_password}
# Restricted runtime role used by both APIs: no DDL, INSERT/SELECT only on the
# audit table. After changing a password here, run setup-postgres.sh again.
POSTGRES_APP_USER=endpoint_app
POSTGRES_APP_PASSWORD=${pg_app_password}

# --- Redis (loopback only) ---------------------------------------------------
# After changing it, run setup-redis.sh again.
REDIS_PASSWORD=${redis_password}

# --- Secret protection (both APIs, identical value) --------------------------
# base64 of 32 random bytes. Rotating only invalidates in-flight secrets.
SECRET_PROTECTION_KEY=${secret_protection_key}

# --- BitLocker recovery-password escrow (Admin API only) ---------------------
# base64 of 32 random bytes. Rotation does NOT re-seal existing rows: bump the
# version and re-seal before retiring the old key. See docs/threat-model.md.
RECOVERY_ESCROW_KEY=${recovery_escrow_key}
RECOVERY_ESCROW_KEY_VERSION=1

# --- Multi-factor authentication (Admin API only) ----------------------------
# base64 of 32 random bytes, sealing the TOTP secret behind each administrator's
# authenticator app. LOSS IS NOT RECOVERABLE BY RE-ENROLLING ONE PERSON: every
# enrolment becomes unreadable at once, and nobody can complete a sign-in.
# Restore it from backup, or reset every account's second factor from the
# database. Never copied into agent-api.env - see AgentApiKeyBoundaryGuard.
MFA_TOTP_KEY=${mfa_totp_key}

# --- Automatic escrow sealing pair (RSA-3072) --------------------------------
# Both empty = automatic escrow switched off, which is the intended initial
# state. See docs/runbooks/escrow-sealing-key.md when enabling it; the private
# half is as backup-critical as RECOVERY_ESCROW_KEY.
RECOVERY_SEALING_PUBLIC_KEY=
RECOVERY_SEALING_PRIVATE_KEY=

# --- Agent release trust mode ------------------------------------------------
# Internal: integrity is the server-computed SHA-256 over HTTPS, no
# Authenticode signature required. Public needs a signer subject as well.
AGENT_RELEASE_TRUST_MODE=Internal
AGENT_RELEASE_SIGNER_SUBJECT=

# --- Public origin -----------------------------------------------------------
# The exact https:// origin browsers and agents use. CORS allow-list; the
# Admin API refuses to start without it.
PUBLIC_ORIGIN=${origin}
EOF

    chmod 600 "$tmp"
    mv "$tmp" "$EPP_SECRETS_FILE"
    trap - EXIT

    echo "==> wrote ${EPP_SECRETS_FILE} (root:root 0600) with:"
    grep -oE '^[A-Z_]+=' "$EPP_SECRETS_FILE" | tr -d '=' | sed 's/^/      /'
    echo "    back this file up: it holds the escrow key and the database passwords"
fi

chown root:root "$EPP_SECRETS_FILE"
chmod 600 "$EPP_SECRETS_FILE"

# --- 2. per-service environment files, every run -----------------------------------

load_env_file "$EPP_SECRETS_FILE"

# Upgrade path. MFA_TOTP_KEY was added after the first deployments, so a
# secrets.env written before it exists is missing the key and would fail the
# required-variable check below. Appending it is the correct repair and is safe:
# a key that is not there yet cannot have sealed anything, so generating one
# destroys nothing. An EXISTING value is never touched - that would silently
# invalidate every enrolment.
if [ -z "${MFA_TOTP_KEY:-}" ]; then
    echo "==> adding MFA_TOTP_KEY to ${EPP_SECRETS_FILE} (multi-factor was enabled after this host was set up)"
    {
        echo ""
        echo "# --- Multi-factor authentication (Admin API only) ----------------------------"
        echo "# Added on $(date -u +%Y-%m-%dT%H:%M:%SZ). Back this up: losing it makes every"
        echo "# authenticator enrolment unreadable at once and nobody can complete a sign-in."
        echo "MFA_TOTP_KEY=$(gen_key)"
    } >> "$EPP_SECRETS_FILE"

    load_env_file "$EPP_SECRETS_FILE"
fi

for required in POSTGRES_DB POSTGRES_SUPERUSER POSTGRES_SUPERUSER_PASSWORD \
                POSTGRES_APP_USER POSTGRES_APP_PASSWORD REDIS_PASSWORD \
                SECRET_PROTECTION_KEY RECOVERY_ESCROW_KEY MFA_TOTP_KEY PUBLIC_ORIGIN; do
    if [ -z "${!required:-}" ]; then
        echo "${EPP_SECRETS_FILE} does not set ${required}; refusing to render service files from it." >&2
        exit 1
    fi
done

# A double quote or a backslash inside a value would change meaning between
# systemd's EnvironmentFile parser and this kit's own reader. Generated values
# never contain either; a hand-edited one that does is stopped here instead of
# becoming a service that cannot authenticate for no visible reason.
for checked in POSTGRES_SUPERUSER_PASSWORD POSTGRES_APP_PASSWORD REDIS_PASSWORD \
               SECRET_PROTECTION_KEY RECOVERY_ESCROW_KEY MFA_TOTP_KEY PUBLIC_ORIGIN \
               RECOVERY_SEALING_PUBLIC_KEY RECOVERY_SEALING_PRIVATE_KEY AGENT_RELEASE_SIGNER_SUBJECT; do
    case "${!checked:-}" in
        *'"'* | *'\'*)
            echo "${checked} contains a double quote or a backslash, which the environment files cannot carry." >&2
            exit 1 ;;
    esac
done
# ';' ends a connection-string field and ',' ends a Redis option.
case "${POSTGRES_SUPERUSER_PASSWORD}${POSTGRES_APP_PASSWORD}" in
    *';'*) echo "a PostgreSQL password contains ';', which would split the connection string." >&2; exit 1 ;;
esac
case "$REDIS_PASSWORD" in
    *','* | *' '*) echo "REDIS_PASSWORD contains ',' or a space, which Redis configuration cannot carry." >&2; exit 1 ;;
esac

pg_port="$(detect_pg_port)"
owner_connection="Host=127.0.0.1;Port=${pg_port};Database=${POSTGRES_DB};Username=${POSTGRES_SUPERUSER};Password=${POSTGRES_SUPERUSER_PASSWORD}"
app_connection="Host=127.0.0.1;Port=${pg_port};Database=${POSTGRES_DB};Username=${POSTGRES_APP_USER};Password=${POSTGRES_APP_PASSWORD}"
redis_connection="127.0.0.1:6379,password=${REDIS_PASSWORD}"

# write_env <file>, KEY=VALUE lines on stdin; every value is wrapped in double quotes.
write_env() {
    local file="$1" tmp_file line key value
    tmp_file="${file}.tmp.$$"
    {
        echo "# Rendered by infra/ubuntu/gen-env.sh from secrets.env. Do not edit: edit"
        echo "# secrets.env and re-run gen-env.sh instead. root:root 0600."
        while IFS= read -r line; do
            [ -n "$line" ] || continue
            key="${line%%=*}"
            value="${line#*=}"
            printf '%s="%s"\n' "$key" "$value"
        done
    } > "$tmp_file"
    chown root:root "$tmp_file"
    chmod 600 "$tmp_file"
    mv "$tmp_file" "$file"
    echo "      ${file}"
}

echo "==> rendering per-service environment files (PostgreSQL port ${pg_port})"

# The ONLY component given the owner credential. The APIs never hold it.
write_env "$EPP_ENV_MIGRATIONS" <<EOF
ENDPOINTPLATFORM_Database__ConnectionString=${owner_connection}
ENDPOINTPLATFORM_Database__RuntimeRoleName=${POSTGRES_APP_USER}
EOF

# Optional lines are omitted entirely when unset, so "not configured" reaches the
# application as an absent key rather than as an empty string.
optional_admin=""
if [ -n "${RECOVERY_SEALING_PUBLIC_KEY:-}" ]; then
    optional_admin+="ENDPOINTPLATFORM_RecoveryEscrow__SealingPublicKey=${RECOVERY_SEALING_PUBLIC_KEY}"$'\n'
fi
if [ -n "${RECOVERY_SEALING_PRIVATE_KEY:-}" ]; then
    optional_admin+="ENDPOINTPLATFORM_RecoveryEscrow__SealingPrivateKey=${RECOVERY_SEALING_PRIVATE_KEY}"$'\n'
fi
if [ -n "${AGENT_RELEASE_SIGNER_SUBJECT:-}" ]; then
    optional_admin+="ENDPOINTPLATFORM_AgentReleases__ExpectedSignerSubject=${AGENT_RELEASE_SIGNER_SUBJECT}"$'\n'
fi

# ASPNETCORE_FORWARDEDHEADERS_ENABLED: outside Development both hosts call
# UseHttpsRedirection() and issue Secure cookies. TLS terminates in nginx, so
# without trusting its X-Forwarded-Proto the app would see plain http. Safe
# here because the APIs listen on loopback only: nothing but nginx reaches them.
write_env "$EPP_ENV_ADMIN_API" <<EOF
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=http://127.0.0.1:${EPP_ADMIN_API_PORT}
ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
ENDPOINTPLATFORM_Database__ConnectionString=${app_connection}
ENDPOINTPLATFORM_Redis__ConnectionString=${redis_connection}
ENDPOINTPLATFORM_SecretProtection__Key=${SECRET_PROTECTION_KEY}
ENDPOINTPLATFORM_Cors__AllowedOrigins__0=${PUBLIC_ORIGIN}
ENDPOINTPLATFORM_PackageStorage__Directory=${EPP_PACKAGES_DIR}
ENDPOINTPLATFORM_AgentReleases__TrustMode=${AGENT_RELEASE_TRUST_MODE:-Internal}
ENDPOINTPLATFORM_RecoveryEscrow__Key=${RECOVERY_ESCROW_KEY}
ENDPOINTPLATFORM_Mfa__TotpKey=${MFA_TOTP_KEY}
ENDPOINTPLATFORM_RecoveryEscrow__KeyVersion=${RECOVERY_ESCROW_KEY_VERSION:-1}
${optional_admin}
EOF

# PUBLIC half of the sealing pair only, and never RECOVERY_ESCROW_KEY:
# AgentApiKeyBoundaryGuard fails this host at startup if either ever appears.
optional_agent=""
if [ -n "${RECOVERY_SEALING_PUBLIC_KEY:-}" ]; then
    optional_agent+="ENDPOINTPLATFORM_RecoveryEscrow__SealingPublicKey=${RECOVERY_SEALING_PUBLIC_KEY}"$'\n'
fi

write_env "$EPP_ENV_AGENT_API" <<EOF
ASPNETCORE_ENVIRONMENT=Production
ASPNETCORE_URLS=http://127.0.0.1:${EPP_AGENT_API_PORT}
ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
ENDPOINTPLATFORM_Database__ConnectionString=${app_connection}
ENDPOINTPLATFORM_Redis__ConnectionString=${redis_connection}
ENDPOINTPLATFORM_SecretProtection__Key=${SECRET_PROTECTION_KEY}
ENDPOINTPLATFORM_PackageStorage__Directory=${EPP_PACKAGES_DIR}
${optional_agent}
EOF

echo
echo "gen-env.sh: done"
